air-discount-scheme-api:
  enabled: true
  env:
    AUTH_AUDIENCE: loftbru.dev01.devland.is
    BACKEND_URL: http://web-air-discount-scheme-backend
    CONTENTFUL_HOST: preview.contentful.com
    ELASTIC_NODE: https://vpc-search-njkekqydiegezhr4vqpkfnw5la.eu-west-1.es.amazonaws.com
    SAML_ENTRY_POINT: https://innskraning.island.is/?id=ads.dev
    SSF_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: /liveness
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: /liveness
      timeoutSeconds: 3
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-api
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: nginx-external-alb
      hosts:
        - host: loftbru.dev01.devland.is
          paths:
            - /api
        - host: loftbru-cf.dev01.devland.is
          paths:
            - /api
  namespace: air-discount-scheme
  podSecurityContext:
    fsGroup: 65534
  replicaCount:
    default: 2
    max: 3
    min: 2
  secrets:
    ADMINS: /k8s/air-discount-scheme/api/ADMINS
    AUTH_JWT_SECRET: /k8s/air-discount-scheme/api/AUTH_JWT_SECRET
    CONFIGCAT_SDK_KEY: /k8s/configcat/CONFIGCAT_SDK_KEY
    CONTENTFUL_ACCESS_TOKEN: /k8s/air-discount-scheme/api/CONTENTFUL_ACCESS_TOKEN
    DEVELOPERS: /k8s/air-discount-scheme/api/DEVELOPERS
    SENTRY_DSN: /k8s/air-discount-scheme-api/SENTRY_DSN
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  serviceAccount:
    annotations:
      eks.amazonaws.com/role-arn: arn:aws:iam::013313053092:role/air-discount-scheme-api
    create: true
    name: air-discount-scheme-api
  strategy:
    type: Recreate
air-discount-scheme-backend:
  enabled: true
  env:
    DB_HOST: dev-vidspyrna-aurora-1.c6cxecmrvlpq.eu-west-1.rds.amazonaws.com
    DB_NAME: air_discount_scheme_backend
    DB_USER: air_discount_scheme_backend
    ENVIRONMENT: dev
    REDIS_URL_NODE_01: >-
      clustercfg.general-redis-cluster-group.5fzau3.euw1.cache.amazonaws.com:6379
    SSF_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: /liveness
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: /liveness
      timeoutSeconds: 3
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-backend
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: nginx-external-alb
        nginx.ingress.kubernetes.io/enable-global-auth: 'false'
      hosts:
        - host: loftbru.dev01.devland.is
          paths:
            - /api/swagger
            - /api/public
        - host: loftbru-cf.dev01.devland.is
          paths:
            - /api/swagger
            - /api/public
  initContainer:
    containers:
      - args:
          - sequelize-cli
          - db:migrate
        command:
          - npx
    env:
      DB_HOST: dev-vidspyrna-aurora-1.c6cxecmrvlpq.eu-west-1.rds.amazonaws.com
      DB_NAME: air_discount_scheme_backend
      DB_USER: air_discount_scheme_backend
      SSF_ON: ''
    secrets:
      DB_PASS: /k8s/air-discount-scheme/backend/DB_PASSWORD
  namespace: air-discount-scheme
  replicaCount:
    default: 2
    max: 3
    min: 2
  secrets:
    CONFIGCAT_SDK_KEY: /k8s/configcat/CONFIGCAT_SDK_KEY
    DB_PASS: /k8s/air-discount-scheme/backend/DB_PASSWORD
    ERNIR_API_KEY: /k8s/air-discount-scheme/backend/ERNIR_API_KEY
    ICELANDAIR_API_KEY: /k8s/air-discount-scheme/backend/ICELANDAIR_API_KEY
    NATIONAL_REGISTRY_PASSWORD: /k8s/air-discount-scheme/backend/NATIONAL_REGISTRY_PASSWORD
    NORLANDAIR_API_KEY: /k8s/air-discount-scheme/backend/NORLANDAIR_API_KEY
    SENTRY_DSN: /k8s/air-discount-scheme-backend/SENTRY_DSN
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  strategy:
    type: Recreate
air-discount-scheme-web:
  enabled: true
  env:
    API_URL: http://web-air-discount-scheme-api
    SSF_ON: ''
  grantNamespaces: []
  grantNamespacesEnabled: false
  healthCheck:
    liveness:
      initialDelaySeconds: 3
      path: /liveness
      timeoutSeconds: 3
    readiness:
      initialDelaySeconds: 3
      path: /readiness
      timeoutSeconds: 3
  image:
    repository: 821090935708.dkr.ecr.eu-west-1.amazonaws.com/air-discount-scheme-web
  ingress:
    primary-alb:
      annotations:
        kubernetes.io/ingress.class: nginx-external-alb
        nginx.ingress.kubernetes.io/configuration-snippet: >-
          rewrite /$ https://beta.dev01.devland.is/loftbru; rewrite /en$
          https://beta.dev01.devland.is/en/lower-airfares-for-residents-in-rural-areas;
      hosts:
        - host: loftbru.dev01.devland.is
          paths:
            - /
        - host: loftbru-cf.dev01.devland.is
          paths:
            - /
  namespace: air-discount-scheme
  replicaCount:
    default: 2
    max: 3
    min: 2
  secrets:
    CONFIGCAT_SDK_KEY: /k8s/configcat/CONFIGCAT_SDK_KEY
    SENTRY_DSN: /k8s/air-discount-scheme-api/SENTRY_DSN
  securityContext:
    allowPrivilegeEscalation: false
    privileged: false
  strategy:
    type: Recreate
global:
  env:
    AUDIT_GROUP_NAME: /island-is/audit-log
    AWS_REGION: eu-west-1
    IDENTITY_SERVER_ISSUER_URL: https://identity-server.dev01.devland.is
    PORT: '3333'
    name: dev
  image:
    tag: latest_master
  initContainer:
    env:
      AWS_REGION: eu-west-1

